  
version: '3'
services:
  vue-ui:
    build:
      context: ./source
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./source:/usr/src/app/source
       - /usr/src/app/source/node_modules