version: '3'
services:
  nodejs-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  vue-ui:
    build:
      context: ./source
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./source:/usr/src/app/source
       - /usr/src/app/source/node_modules